/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'milesd' at '11/08/15 21:20' with Gradle 2.2.1
 *
 * @author milesd, @date 11/08/15 21:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
